server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tik_handle? serverTimezone=UTC
    username: root
    password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
